# Generated by Django 6.0.1 on 2026-04-15 05:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_jobdriverassignment_on_site_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clocked_out_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_entries', to='myapp.driver')),
            ],
            options={
                'ordering': ['-clocked_in_at'],
            },
        ),
    ]
