# Generated by Django 6.0.1 on 2026-04-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_ticket_ticketphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdriverassignment',
            name='backhaul_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdriverassignment',
            name='backhaul_on_site_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdriverassignment',
            name='backhaul_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdriverassignment',
            name='backhaul_status',
            field=models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('en_route', 'En Route'), ('on_site', 'On Site'), ('completed', 'Completed')], max_length=20, null=True),
        ),
    ]
